index:
    path: /
    controller: App\Controller\DefaultController::index

app_adventure_play_game:
    path: /adventure/play
    controller: App\Controller\AdventureController::playGame

app_adventure_move:
    path: /adventure/move
    controller: App\Controller\AdventureController::move
    methods: post

app_adventure_pick:
    path: /adventure/pick
    controller: App\Controller\AdventureController::pickUp
    methods: post

app_adventure_use_item:
    path: /adventure/use
    controller: App\Controller\AdventureController::useItem
    methods: post